### ISSUE TITLE
Is this the behaviour we want? is_valid function returns input variable

### ISSUE THREAD

**Issue by eurunuela** [smoia/phys2bids#50]
As I'm working on the unit tests, I've just seen that the `is_valid` function returns the input variable. Doesn't it make more sense for it to be a void function? If the variable is not valid, it could raise an error, but do nothing otherwise.
 
https://github.com/smoia/phys2bids/blob/f2d7d52e4e9d9d963f98aeb8809c81660e2f1794/phys2bids/physio_obj.py#L37

**Comment by smoia** [comment]
Now it's like that because it's used during the assignment of properties in the __init__ of our objects.
At the moment, there's fewer cases for it to assign to void than for assign to a variable.
This said, it's true that before either your or @rmarkello 's review in #38 it returned something depending on an input parameter (`return_val=True`).
For me it's a way to put it in a pipe, and it can be extended if we need it later on in a similar way to keep the code neat.
I also understand the idea behind this issue, so although I prefer this way it's not a strong preference.
